### PR TITLE
Allow purifycss-webpack to work with ExtractTextCssPlugin when hash is in CSS asset name

### PR DESCRIPTION
**Pull request by IAMtheIAM**
Allow purifycss-webpack to work with ExtractTextCssPlugin when hash is added to css file name. 

Example: [name].css?[hash] -> style.css?218aa9358a709a5a0a12

### CODE REVIEW

**Comment by bebraw** [comment]
Can you add a test below `search.test.js`? The CI should pass too. Good enough after that.

**Comment by bebraw** [comment]
About CI, looks like an existing search test fails with the new logic so the code may require some tweaking not to break the old logic.

**Comment by IAMtheIAM** [comment]
The test is very strict and I don't understand what it is saying.  It doesn't like curly braces around the function:
Before
```
//passes
    name => extensions.indexOf(path.extname(name)) >= 0 && { name, asset: assets[name] }
```
After
```
//fails
    name => { 
         extensions.indexOf(path.extname(name)) >= 0 && { name, asset: assets[name] } 
}
```
However it won't let me add an variables or conditions in that section without curly brace, it warns `{ expected`
```
//fails
    name => {
      var nameCleaned = name;
      if (/\.(css\?).*$/.test(name)) {
        nameCleaned = name.substr(0, name.lastIndexOf('?')); // ignore hash on file like style.css?7ec000f0d0d347
      }
      extensions.indexOf(path.extname(nameCleaned)) >= 0 && { name, asset: assets[name] }
    }
```
So I don't know how to fix it without some guidance about what the test wants.

**Comment by bebraw** [comment]
No probs. I'll try to figure out a fix. 👍

**Comment by bebraw** [comment]
Ah... If you want multiple lines, you could use `name => ( ... )`. That should be equivalent to a single line. With curlies it won't return by default.

**Comment by IAMtheIAM** [comment]
Got it working. Still learning ES6 syntax :-)

**Pull request merged**
